# Generated by Django 3.0.5 on 2020-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=140, null=True, verbose_name='Fornavn')),
                ('lastName', models.CharField(max_length=140, null=True, verbose_name='Etternavn')),
                ('department', models.CharField(max_length=140, null=True, verbose_name='Avdeling')),
                ('type', models.IntegerField(choices=[(0, '--------'), (1, 'Løping'), (2, 'Styrke'), (3, 'Sykling'), (4, 'Gåing'), (5, 'Ski'), (6, 'Svømming')], default=0)),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distanse')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Registrering',
                'verbose_name_plural': 'Registreringer',
                'ordering': ['firstName'],
            },
        ),
    ]
