# Generated by Django 3.0.5 on 2020-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrering',
            name='comment',
            field=models.TextField(null=True, verbose_name='Kommentar'),
        ),
    ]
