# Generated by Django 3.0.5 on 2020-04-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stefan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrering',
        ),
    ]
