# Generated by Django 3.0.5 on 2020-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefan', '0002_registrering_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrering',
            name='type',
            field=models.IntegerField(choices=[(0, 'Styrke'), (0, 'Løping'), (0, 'Sykling'), (0, 'Gåing'), (0, 'Ski'), (0, 'Svømming')], default=0),
        ),
    ]
