# Generated by Django 3.0.5 on 2020-04-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefan', '0003_registrering_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrering',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distanse'),
        ),
        migrations.AlterField(
            model_name='registrering',
            name='type',
            field=models.IntegerField(choices=[(0, '--------'), (1, 'Løping'), (2, 'Styrke'), (3, 'Sykling'), (4, 'Gåing'), (5, 'Ski'), (6, 'Svømming')], default=0),
        ),
    ]
