# Generated by Django 3.0.5 on 2020-04-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefan', '0004_auto_20200406_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrering',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
