# Generated by Django 3.0.5 on 2020-04-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=140, null=True, verbose_name='Avdeling'),
        ),
    ]
