# Generated by Django 3.0.5 on 2020-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200409_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, '-----'), ('M', 'Mann'), ('F', 'Kvinne'), ('O', 'Annet')], default=None, max_length=1, null=True, verbose_name='Kjønn'),
        ),
    ]
