# Generated by Django 3.0.5 on 2020-04-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200410_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Avdeling', 'verbose_name_plural': 'Avdelinger'},
        ),
    ]
