# Generated by Django 3.0.5 on 2020-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200412_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Avdeling'),
        ),
    ]
