# Generated by Django 3.0.5 on 2020-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200412_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['employee_nr'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_nr',
            field=models.PositiveIntegerField(default=None, unique=True, verbose_name='Ansatt nummer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Kallenavn'),
        ),
    ]
