# Generated by Django 3.0.5 on 2020-04-07 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '------'), (1, 'styrke'), (2, 'løping'), (3, 'sykling'), (4, 'gåing'), (5, 'svømming'), (6, 'ski')], default=0, verbose_name='Treningstype')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distanse')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Dato')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name': 'Treningsøkt',
                'verbose_name_plural': 'Treningsøkter',
                'ordering': ['-id'],
            },
        ),
    ]
