# Generated by Django 3.0.5 on 2020-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emil', '0002_auto_20200408_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
