# Generated by Django 3.0.5 on 2020-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140, null=True, verbose_name='Fornavn')),
                ('last_name', models.CharField(max_length=140, null=True, verbose_name='Etternavn')),
                ('department', models.CharField(max_length=140, null=True, verbose_name='Avdeling')),
                ('distance', models.FloatField(null=True, verbose_name='Distanse')),
            ],
            options={
                'verbose_name': 'Registrering',
                'verbose_name_plural': 'Registreringer',
                'ordering': ['first_name'],
            },
        ),
    ]
