# Generated by Django 3.0.5 on 2020-04-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrering',
            options={'verbose_name': 'Registrering', 'verbose_name_plural': 'Registreringer'},
        ),
        migrations.RemoveField(
            model_name='registrering',
            name='department',
        ),
        migrations.RemoveField(
            model_name='registrering',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registrering',
            name='last_name',
        ),
    ]
