# Generated by Django 3.0.5 on 2020-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_registrering_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrering',
            name='type',
            field=models.IntegerField(choices=[(0, '------'), (1, 'styrke'), (2, 'løping'), (3, 'sykling'), (4, 'gåing'), (5, 'svømming'), (6, 'ski')], default=0, verbose_name='Treningstype'),
        ),
    ]
