# Generated by Django 3.0.5 on 2020-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_auto_20200409_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True, verbose_name='Distanse'),
        ),
    ]
