# Generated by Django 3.0.5 on 2020-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_registrering_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrering',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distanse'),
        ),
    ]
