# Generated by Django 3.0.5 on 2020-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0004_auto_20200410_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distanse'),
        ),
    ]
