# Generated by Django 3.0.5 on 2020-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0005_auto_20200412_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.IntegerField(choices=[(0, '------'), (1, 'Styrke'), (2, 'Løping'), (3, 'Sykling'), (4, 'Gåing'), (5, 'Svømming'), (6, 'Ski')], default=0, verbose_name='Treningstype'),
        ),
    ]
